target-version = "py312"
line-length = 80
src = ["src", "tests"]

[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "PT",   # flake8-pytest-style
    "RUF",  # ruff-specific rules
    "ANN",  # flake8-annotations
    "ERA",  # eradicate (commented-out code)
    "PIE",  # flake8-pie
    "TRY",  # tryceratops
    "PERF", # perflint
]
ignore = [
    "ANN101", # missing type annotation for `self`
    "ANN102", # missing type annotation for `cls`
    "TRY003", # avoid specifying long messages outside exception class
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN",  # no type annotations required in tests
    "S101", # allow assert in tests
]

[lint.isort]
known-first-party = ["dsl"]
force-sort-within-sections = true

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
