import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsEnum, IsOptional, IsUUID } from "class-validator";
import { SsoSurface } from "../schemas/sso-token.schema";

export class SsoGenerateDto {
    @ApiProperty({ enum: SsoSurface, example: SsoSurface.JAVA_DESKTOP })
    @IsEnum(SsoSurface)
    surface: SsoSurface;

    @ApiPropertyOptional({
        example: "550e8400-e29b-41d4-a716-446655440000",
        description:
            "PKCE-style state — UUID v4 generated by the desktop client for CSRF protection",
    })
    @IsOptional()
    @IsUUID(4)
    state?: string;
}

export class SsoGenerateResponseDto {
    @ApiProperty({ example: "550e8400-e29b-41d4-a716-446655440000" })
    ssoToken: string;

    @ApiProperty({ example: "2026-04-05T12:30:00.000Z" })
    expiresAt: string;

    @ApiProperty({ example: 300 })
    expiresIn: number;
}
