/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SsoAuthorizeRouteImport } from './routes/sso/authorize'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppNeighborhoodsIndexRouteImport } from './routes/_app/neighborhoods/index'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app/incidents/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDslIndexRouteImport } from './routes/_app/dsl/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCommunityVotesIndexRouteImport } from './routes/_app/community-votes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoAuthorizeRoute = SsoAuthorizeRouteImport.update({
  id: '/sso/authorize',
  path: '/sso/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppNeighborhoodsIndexRoute = AppNeighborhoodsIndexRouteImport.update({
  id: '/neighborhoods/',
  path: '/neighborhoods/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDslIndexRoute = AppDslIndexRouteImport.update({
  id: '/dsl/',
  path: '/dsl/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityVotesIndexRoute = AppCommunityVotesIndexRouteImport.update({
  id: '/community-votes/',
  path: '/community-votes/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso/authorize': typeof SsoAuthorizeRoute
  '/community-votes/': typeof AppCommunityVotesIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dsl/': typeof AppDslIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/incidents/': typeof AppIncidentsIndexRoute
  '/neighborhoods/': typeof AppNeighborhoodsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sso/authorize': typeof SsoAuthorizeRoute
  '/community-votes': typeof AppCommunityVotesIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dsl': typeof AppDslIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/incidents': typeof AppIncidentsIndexRoute
  '/neighborhoods': typeof AppNeighborhoodsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sso/authorize': typeof SsoAuthorizeRoute
  '/_app/community-votes/': typeof AppCommunityVotesIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dsl/': typeof AppDslIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
  '/_app/neighborhoods/': typeof AppNeighborhoodsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sso/authorize'
    | '/community-votes/'
    | '/dashboard/'
    | '/dsl/'
    | '/events/'
    | '/incidents/'
    | '/neighborhoods/'
    | '/services/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sso/authorize'
    | '/community-votes'
    | '/dashboard'
    | '/dsl'
    | '/events'
    | '/incidents'
    | '/neighborhoods'
    | '/services'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sso/authorize'
    | '/_app/community-votes/'
    | '/_app/dashboard/'
    | '/_app/dsl/'
    | '/_app/events/'
    | '/_app/incidents/'
    | '/_app/neighborhoods/'
    | '/_app/services/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SsoAuthorizeRoute: typeof SsoAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso/authorize': {
      id: '/sso/authorize'
      path: '/sso/authorize'
      fullPath: '/sso/authorize'
      preLoaderRoute: typeof SsoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/neighborhoods/': {
      id: '/_app/neighborhoods/'
      path: '/neighborhoods'
      fullPath: '/neighborhoods/'
      preLoaderRoute: typeof AppNeighborhoodsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dsl/': {
      id: '/_app/dsl/'
      path: '/dsl'
      fullPath: '/dsl/'
      preLoaderRoute: typeof AppDslIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community-votes/': {
      id: '/_app/community-votes/'
      path: '/community-votes'
      fullPath: '/community-votes/'
      preLoaderRoute: typeof AppCommunityVotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCommunityVotesIndexRoute: typeof AppCommunityVotesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDslIndexRoute: typeof AppDslIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
  AppNeighborhoodsIndexRoute: typeof AppNeighborhoodsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityVotesIndexRoute: AppCommunityVotesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDslIndexRoute: AppDslIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
  AppNeighborhoodsIndexRoute: AppNeighborhoodsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SsoAuthorizeRoute: SsoAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
