FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/client/package.json ./apps/client/
COPY apps/back-office/package.json ./apps/back-office/
COPY packages/ui/package.json ./packages/ui/

RUN pnpm install

EXPOSE 5173 5174
