/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingPendingRouteImport } from './routes/onboarding/pending'
import { Route as OnboardingAddressRouteImport } from './routes/onboarding/address'
import { Route as AppVotesIndexRouteImport } from './routes/_app/votes/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppRecommendationsIndexRouteImport } from './routes/_app/recommendations/index'
import { Route as AppPointsIndexRouteImport } from './routes/_app/points/index'
import { Route as AppMessagesIndexRouteImport } from './routes/_app/messages/index'
import { Route as AppIncidentsIndexRouteImport } from './routes/_app/incidents/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppContractsIndexRouteImport } from './routes/_app/contracts/index'
import { Route as AppBookingsIndexRouteImport } from './routes/_app/bookings/index'
import { Route as AppServicesMineRouteImport } from './routes/_app/services/mine'
import { Route as AppIncidentsIdRouteImport } from './routes/_app/incidents/$id'
import { Route as AppContractsIdRouteImport } from './routes/_app/contracts/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPendingRoute = OnboardingPendingRouteImport.update({
  id: '/onboarding/pending',
  path: '/onboarding/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAddressRoute = OnboardingAddressRouteImport.update({
  id: '/onboarding/address',
  path: '/onboarding/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVotesIndexRoute = AppVotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsIndexRoute = AppRecommendationsIndexRouteImport.update({
  id: '/recommendations/',
  path: '/recommendations/',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsIndexRoute = AppPointsIndexRouteImport.update({
  id: '/points/',
  path: '/points/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIndexRoute = AppIncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIndexRoute = AppContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesMineRoute = AppServicesMineRouteImport.update({
  id: '/services/mine',
  path: '/services/mine',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsIdRoute = AppIncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsIdRoute = AppContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding/address': typeof OnboardingAddressRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/contracts/$id': typeof AppContractsIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/services/mine': typeof AppServicesMineRoute
  '/bookings/': typeof AppBookingsIndexRoute
  '/contracts/': typeof AppContractsIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/incidents/': typeof AppIncidentsIndexRoute
  '/messages/': typeof AppMessagesIndexRoute
  '/points/': typeof AppPointsIndexRoute
  '/recommendations/': typeof AppRecommendationsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/votes/': typeof AppVotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding/address': typeof OnboardingAddressRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/contracts/$id': typeof AppContractsIdRoute
  '/incidents/$id': typeof AppIncidentsIdRoute
  '/services/mine': typeof AppServicesMineRoute
  '/bookings': typeof AppBookingsIndexRoute
  '/contracts': typeof AppContractsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/incidents': typeof AppIncidentsIndexRoute
  '/messages': typeof AppMessagesIndexRoute
  '/points': typeof AppPointsIndexRoute
  '/recommendations': typeof AppRecommendationsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/votes': typeof AppVotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding/address': typeof OnboardingAddressRoute
  '/onboarding/pending': typeof OnboardingPendingRoute
  '/_app/contracts/$id': typeof AppContractsIdRoute
  '/_app/incidents/$id': typeof AppIncidentsIdRoute
  '/_app/services/mine': typeof AppServicesMineRoute
  '/_app/bookings/': typeof AppBookingsIndexRoute
  '/_app/contracts/': typeof AppContractsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/incidents/': typeof AppIncidentsIndexRoute
  '/_app/messages/': typeof AppMessagesIndexRoute
  '/_app/points/': typeof AppPointsIndexRoute
  '/_app/recommendations/': typeof AppRecommendationsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/votes/': typeof AppVotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/onboarding/address'
    | '/onboarding/pending'
    | '/contracts/$id'
    | '/incidents/$id'
    | '/services/mine'
    | '/bookings/'
    | '/contracts/'
    | '/dashboard/'
    | '/events/'
    | '/incidents/'
    | '/messages/'
    | '/points/'
    | '/recommendations/'
    | '/services/'
    | '/settings/'
    | '/votes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/onboarding/address'
    | '/onboarding/pending'
    | '/contracts/$id'
    | '/incidents/$id'
    | '/services/mine'
    | '/bookings'
    | '/contracts'
    | '/dashboard'
    | '/events'
    | '/incidents'
    | '/messages'
    | '/points'
    | '/recommendations'
    | '/services'
    | '/settings'
    | '/votes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/onboarding/address'
    | '/onboarding/pending'
    | '/_app/contracts/$id'
    | '/_app/incidents/$id'
    | '/_app/services/mine'
    | '/_app/bookings/'
    | '/_app/contracts/'
    | '/_app/dashboard/'
    | '/_app/events/'
    | '/_app/incidents/'
    | '/_app/messages/'
    | '/_app/points/'
    | '/_app/recommendations/'
    | '/_app/services/'
    | '/_app/settings/'
    | '/_app/votes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OnboardingAddressRoute: typeof OnboardingAddressRoute
  OnboardingPendingRoute: typeof OnboardingPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/pending': {
      id: '/onboarding/pending'
      path: '/onboarding/pending'
      fullPath: '/onboarding/pending'
      preLoaderRoute: typeof OnboardingPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/address': {
      id: '/onboarding/address'
      path: '/onboarding/address'
      fullPath: '/onboarding/address'
      preLoaderRoute: typeof OnboardingAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/votes/': {
      id: '/_app/votes/'
      path: '/votes'
      fullPath: '/votes/'
      preLoaderRoute: typeof AppVotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations/': {
      id: '/_app/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof AppRecommendationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/': {
      id: '/_app/points/'
      path: '/points'
      fullPath: '/points/'
      preLoaderRoute: typeof AppPointsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages/': {
      id: '/_app/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/': {
      id: '/_app/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AppIncidentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/': {
      id: '/_app/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AppContractsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/': {
      id: '/_app/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/mine': {
      id: '/_app/services/mine'
      path: '/services/mine'
      fullPath: '/services/mine'
      preLoaderRoute: typeof AppServicesMineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents/$id': {
      id: '/_app/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof AppIncidentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts/$id': {
      id: '/_app/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AppContractsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContractsIdRoute: typeof AppContractsIdRoute
  AppIncidentsIdRoute: typeof AppIncidentsIdRoute
  AppServicesMineRoute: typeof AppServicesMineRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppContractsIndexRoute: typeof AppContractsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppIncidentsIndexRoute: typeof AppIncidentsIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppPointsIndexRoute: typeof AppPointsIndexRoute
  AppRecommendationsIndexRoute: typeof AppRecommendationsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppVotesIndexRoute: typeof AppVotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContractsIdRoute: AppContractsIdRoute,
  AppIncidentsIdRoute: AppIncidentsIdRoute,
  AppServicesMineRoute: AppServicesMineRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppContractsIndexRoute: AppContractsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppIncidentsIndexRoute: AppIncidentsIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppPointsIndexRoute: AppPointsIndexRoute,
  AppRecommendationsIndexRoute: AppRecommendationsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppVotesIndexRoute: AppVotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OnboardingAddressRoute: OnboardingAddressRoute,
  OnboardingPendingRoute: OnboardingPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
