import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";

export class DslQueryResultDto {
    @ApiProperty({
        example: "find",
        enum: ["find", "count"],
        description: "Type of the compiled DSL query",
    })
    type: string;

    @ApiProperty({
        example: "incidents",
        enum: ["incidents", "services", "events", "neighborhoods"],
    })
    collection: string;

    @ApiProperty({
        example: { status: "open" },
        description: "MongoDB filter generated by the DSL compiler",
    })
    filter: Record<string, unknown>;

    @ApiPropertyOptional({
        example: 10,
        description: "Result limit (LIMIT clause)",
    })
    limit?: number;

    @ApiPropertyOptional({
        example: [
            { id: "uuid-1", title: "Broken streetlight", status: "open" },
        ],
        description: "Documents returned by the find query (absent for count)",
    })
    results?: unknown[];

    @ApiPropertyOptional({
        example: 5,
        description: "Number of documents (only for COUNT queries)",
    })
    count?: number;
}
